package uk.ac.rgu.rgtodu.data;

import android.content.Context;
import android.util.Log;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Random;

/**
 * This class provides the single point of truth in the app for {@link TaskRepository}s, and
 * will in the future deal with downloading, storing, and retrieving them.
 * @author  David Corsar
 */
public class TaskRepository {

    // tag for logging
    private static final String TAG = "TaskRepository";

    /**
     * A field for how dates should be formatted before displaying to users
     * with the day of the month as a number, and the month as text
     */
    private static final String DATE_FORMAT = "dd MMM";

    /**
     * The Singleton instance for this repository
     */
    private static TaskRepository INSTANCE;

    /**
     * The Context that the app is operating within
     */
    private Context context;

    /**
     * Create a new @{@link TaskRepository}
     * @param context The {@link Context} for the database to operate in
     */
    private TaskRepository(Context context){
        super();
        this.context = context;

    }

    /**
     * Gets the singleton {@link TaskRepository} for use when managing {@link Task}s
     * in the app.
     * @return The {@link TaskRepository} to be used for managing {@link Task}s in the app.
     */
    public static TaskRepository getRepository(Context context){
        if (INSTANCE == null){
            synchronized (TaskRepository.class) {
                if (INSTANCE == null)
                    INSTANCE = new TaskRepository(context);
            }
        }
        return INSTANCE;
    }

    /**
     * Returns a fake Task for testing purposes
     * @return a fake {@link Task} for testing
     */

    public Task getTask(){
        return getSyntheticTask();
    }

    /**
     * Gets all the tasks in the database
     * @return a {@link List} of sample {@link Task} entities for testing
     */
    public List<Task> getAllTasks(){
        return getSyntheticTasks(20);
    }

    /**
     * Returns a list containing the specified number of Tasks generated by getTask
     * @param number The number of Tasks to return
     * @return
     */
    private List<Task> getSyntheticTasks(int number){
        List<Task> tasks = new ArrayList<>(number);
        for (int i = 0; i < number; i++){
            Task t = getSyntheticTask();

            tasks.add(t);
        }
        return tasks;
    }

    /**
     * Returns a {@link Task} with randomly generated info.
     * @return a {@link Task} for tomorrow, with randomly generated details.
     */
    public Task getSyntheticTask(){
        // create a new Task
        Task t = new Task();

        // A random number generator for populating the fields
        Random random = new Random();

        int id = random.nextInt(10000);
        // set the name randomly
        t.setName(String.format("Task %s", id));

        // set the description to some placeholder
        t.setObjective("Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.");

        // set estimated hours to completely to be random between 1 and 5
        t.setPomodorosRemaining(random.nextInt(5));

        // set the priority randomly
        t.setPriority(TaskPriority.values()[random.nextInt(3)]);

        // set the status randomly
        t.setStatus(TaskStatus.values()[random.nextInt(3)]);

        // schedule it for up to 14 days in the future
        long offset = 1000*60*60*24 * random.nextInt(14);
        t.setDeadline(new Date(System.currentTimeMillis() + offset));

        return t;
    }


    /**
     * Stores task in the database
     * @param task The {@link Task} to store in the Room database.
     */
    public void storeTask(Task task){
        // todo store task
        Log.d(TAG, "Saving task " + task);
    }

    /**
     * Stores the list of tasks in the database
     * @param tasks The {@link List} of {@link Task}s to store in the Room database.
     */
    public void storeTasks(List<Task> tasks){
       // todo store task

    }

    /**
     * Updates task in the database
     * @param task The {@link Task} to store in the Room database.
     */
    public void updateTask(Task task){
      // todo update task
    }

    /**
     * Stores the list of tasks in the database
     * @param tasks The {@link List} of {@link Task}s to store in the Room database.
     */
    public void updateTasks(List<Task> tasks){
       // todo update tasks
    }

    /**
     * Deletes task from the database
     * @param task The {@link Task} to delete from the Room database.
     */
    public void deleteTask(Task task){
       // todo delete task
    }






}
